### ISSUE TITLE
No number on section and subsection

### ISSUE THREAD

**Issue by FirstHandScientist** [mschroen/review_response_letter#3]
Thank you for the nice templates.
I have one problem on the AR_to_RC.tex template. It compiles without error but there is no numbering for sections and subsections.

Any idea on this?

**Comment by mschroen** [comment]
Are you compiling from `.md` or `.tex`? If you compile Markdown using pandoc, try to add the `-N` parameter for section numbering (see [pandoc guide](https://pandoc.org/MANUAL.html)). I.e., add it to [AR_to_RC/make-md.bat](https://github.com/mschroen/review_response_letter/blob/master/AR_to_RC/make-md.bat).

**Comment by mschroen** [comment]
Considered solved.
